# Set this website's info
# Change "coffeebank" to your GitHub username
# Change "moonrise" to your repository name
url: "https://wisdra.com"
baseurl: "/"
siteIcon: /media/android-chrome-192x192.png
siteYear: 2025
siteFooterlink: /about
showinSearchEngines: true
googleAnalyticsID: G-SGCNM11NQR


# Set basic server info
serverName: WISdra SMP
serverDescription: Civilization style Towny server with dynamic economy, nations, and strategic gameplay!
serverIP: mc.wisdra.com:25565
useBedrockForOnlineStatus: false


# Discord information
discordInvite: https://discord.wisdra.com
discordServerID: 1290733391427408027
discordChannelID: 1290737592655937556


# # Navbar Links at the top of the page (uncomment "siteNav" to use)
# #   name - The title on the navbar
# #   url - The link it should go to (for example, if you have "maps.md" file, put "maps")
# #   newtab - Whether link should open in new tab
# 
siteNav:
  - name: Server Map
    url: map
    newtab: true
  - name: Store
    url: store
    newtab: true
  - name: About
    url: about


# Don't change anything below here, these are defaults set by GitHub Pages:
# ======
theme: minima
# plugins:
#   - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/